### ISSUE TITLE
About line 16 in Algorithm2

### ISSUE THREAD

**Issue by WalterMadelim** [rchen234/SIP_LAG#1]
Hi, Dr. Chen.
I'm reading your paper, and find that there is a \hat on top of $\hat Q_s^*$, at line 16 in Algorithm 2.
This line suggests that we should add a Lagrangian cut when the current trial point (1st stage solution) violates a Lag-cut.
But I'm not clear about why do you use the $\hat Q$ ( eq(18) ) instead of $Q$ ( eq(12) ) itself.
After reading your code `master.py`, I would prefer to deem that you do this (add the \hat) on purpose.
Could you tell me the rationale? Thanks.

**Comment by rchen234** [comment]
Hi @WalterMadelim ,

Thanks for your interest in our work! I think $`\hat{Q}^*_s(\pi^{t,s},\pi_0^{t,s})=Q_s^*(\pi^{t,s},\pi_0^{t,s})`$ in this case because $(\pi^{t,s},\pi_0^{t,s})$ has been evaluated in Algorithm 1 (the associated optimal solution is added to $\hat{E}^s$ at line 4 in Algorithm 1 and therefore the cutting plane approximation is tight there). We use $`\hat{Q}^*_s(\pi^{t,s},\pi_0^{t,s})`$ at line 16 in Algorithm 2 to emphasize that there is no need to reevaluate $`Q_s^*(\pi^{t,s},\pi_0^{t,s})`$.

I hope that answers your question. Let me know if there is anything unclear.

Rui

**Comment by WalterMadelim** [comment]
That sounds like a delicate design!👍
